### ISSUE TITLE
lambda question

### ISSUE THREAD

**Issue by amymhaddad** [amymhaddad/version_2_exercises_for_programmers#14]
In the code below, I wrote two lambda expressions instead of two functions. Is this a good time to use lambda? Otherwise, the functions would've been super short. If so, do I have to do something special to get the function to print correctly? I'm not sure why the error is this:` <function main.<locals>.<lambda> at 0x1080e8c80>`.

```
import random
ANSWERS = ['yes', 'no', 'maybe', 'ask again later']

def main():
    question = input("What's your question? ")

    random_index = lambda ANSWERS: random.randint(0, len(ANSWERS)-1)
    random_response = lambda ANSWERS: ANSWERS[random_answer]

    print(random_index)

main()
```

**Comment by paulghaddad** [comment]
@amymhaddad This one would be easier to pair on!
